# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: distributed_training.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'distributed_training.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64istributed_training.proto\x12\x14\x64istributed_training\">\n\x0fRegisterRequest\x12\x13\n\x0bworker_name\x18\x01 \x01(\t\x12\x16\n\x0eworker_address\x18\x02 \x01(\t\"G\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tworker_id\x18\x03 \x01(\x05\"2\n\x0e\x46orwardRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\r\n\x05input\x18\x02 \x01(\x0c\"!\n\x0f\x46orwardResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\"9\n\x0f\x42\x61\x63kwardRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\x12\x13\n\x0bgrad_output\x18\x02 \x01(\x0c\"&\n\x10\x42\x61\x63kwardResponse\x12\x12\n\ngrad_input\x18\x01 \x01(\x0c\"%\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\x8b\x03\n\x0fTrainingService\x12_\n\x0eRegisterWorker\x12%.distributed_training.RegisterRequest\x1a&.distributed_training.RegisterResponse\x12Z\n\x0b\x46orwardPass\x12$.distributed_training.ForwardRequest\x1a%.distributed_training.ForwardResponse\x12]\n\x0c\x42\x61\x63kwardPass\x12%.distributed_training.BackwardRequest\x1a&.distributed_training.BackwardResponse\x12\\\n\tHeartbeat\x12&.distributed_training.HeartbeatRequest\x1a\'.distributed_training.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_training_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=52
  _globals['_REGISTERREQUEST']._serialized_end=114
  _globals['_REGISTERRESPONSE']._serialized_start=116
  _globals['_REGISTERRESPONSE']._serialized_end=187
  _globals['_FORWARDREQUEST']._serialized_start=189
  _globals['_FORWARDREQUEST']._serialized_end=239
  _globals['_FORWARDRESPONSE']._serialized_start=241
  _globals['_FORWARDRESPONSE']._serialized_end=274
  _globals['_BACKWARDREQUEST']._serialized_start=276
  _globals['_BACKWARDREQUEST']._serialized_end=333
  _globals['_BACKWARDRESPONSE']._serialized_start=335
  _globals['_BACKWARDRESPONSE']._serialized_end=373
  _globals['_HEARTBEATREQUEST']._serialized_start=375
  _globals['_HEARTBEATREQUEST']._serialized_end=412
  _globals['_HEARTBEATRESPONSE']._serialized_start=414
  _globals['_HEARTBEATRESPONSE']._serialized_end=448
  _globals['_TRAININGSERVICE']._serialized_start=451
  _globals['_TRAININGSERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
